const badgeDefinitions = [
  {
    id: 'unique_restaurants',
    label: 'Restaurant Explorer',
    description: 'Order from different restaurants to expand your food universe.',
    icon: '🧭',
    metric: 'uniqueRestaurantsCount',
    tiers: [
      { tier: 'bronze', threshold: 3 },
      { tier: 'silver', threshold: 5 },
      { tier: 'gold', threshold: 10 },
      { tier: 'diamond', threshold: 20 },
    ],
  },
  {
    id: 'total_orders',
    label: 'Frequent Diner',
    description: 'Place orders regularly and become one of our most active diners.',
    icon: '🍽️',
    metric: 'totalOrdersCount',
    tiers: [
      { tier: 'bronze', threshold: 5 },
      { tier: 'silver', threshold: 10 },
      { tier: 'gold', threshold: 25 },
      { tier: 'diamond', threshold: 50 },
    ],
  },
  {
    id: 'streak_days',
    label: 'Streak Master',
    description: 'Keep your daily ordering streak going without a break.',
    icon: '🔥',
    metric: 'maxStreakDays',
    tiers: [
      { tier: 'bronze', threshold: 3 },
      { tier: 'silver', threshold: 7 },
      { tier: 'gold', threshold: 14 },
      { tier: 'diamond', threshold: 30 },
    ],
  },
  {
    id: 'lifetime_spend',
    label: 'Lifetime Spender',
    description: 'Accumulate total spending across all your orders.',
    icon: '💰',
    metric: 'lifetimeSpend',
    tiers: [
      { tier: 'bronze', threshold: 100 },
      { tier: 'silver', threshold: 250 },
      { tier: 'gold', threshold: 500 },
      { tier: 'diamond', threshold: 1000 },
    ],
  },
  {
    id: 'high_value_orders',
    label: 'Big Ticket Orders',
    description: 'Place orders above $40.',
    icon: '💎',
    metric: 'highValueOrdersCount',
    tiers: [
      { tier: 'bronze', threshold: 1 },
      { tier: 'silver', threshold: 3 },
      { tier: 'gold', threshold: 5 },
      { tier: 'diamond', threshold: 10 },
    ],
  },
  {
    id: 'review_count',
    label: 'Top Reviewer',
    description: 'Share your thoughts by leaving reviews.',
    icon: '✍️',
    metric: 'totalReviewsCount',
    tiers: [
      { tier: 'bronze', threshold: 1 },
      { tier: 'silver', threshold: 5 },
      { tier: 'gold', threshold: 10 },
      { tier: 'diamond', threshold: 20 },
    ],
  },
  {
    id: 'one_star_reviews',
    label: 'Harsh Critic',
    description: 'You are not afraid to speak up when things go wrong.',
    icon: '⭐',
    metric: 'oneStarReviewsCount',
    tiers: [
      { tier: 'bronze', threshold: 1 },
      { tier: 'silver', threshold: 3 },
      { tier: 'gold', threshold: 5 },
      { tier: 'diamond', threshold: 10 },
    ],
  },
  {
    id: 'five_star_reviews',
    label: 'Hype Builder',
    description: 'Celebrate your favorite places with 5-star reviews.',
    icon: '🌟',
    metric: 'fiveStarReviewsCount',
    tiers: [
      { tier: 'bronze', threshold: 1 },
      { tier: 'silver', threshold: 5 },
      { tier: 'gold', threshold: 10 },
      { tier: 'diamond', threshold: 20 },
    ],
  },
  {
    id: 'repeat_restaurant_loyalty',
    label: 'Loyal Regular',
    description: 'Keep coming back to the same spot over and over again.',
    icon: '🏠',
    metric: 'sameRestaurantMaxOrders',
    tiers: [
      { tier: 'bronze', threshold: 3 },
      { tier: 'silver', threshold: 5 },
      { tier: 'gold', threshold: 10 },
      { tier: 'diamond', threshold: 20 },
    ],
  },
  {
    id: 'friday_orders',
    label: 'Friday Foodie',
    description: 'Make Friday your regular takeout day.',
    icon: '📅',
    metric: 'fridayOrdersCount',
    tiers: [
      { tier: 'bronze', threshold: 3 },
      { tier: 'silver', threshold: 5 },
      { tier: 'gold', threshold: 10 },
      { tier: 'diamond', threshold: 20 },
    ],
  },
  {
    id: 'late_night_orders',
    label: 'Night Owl',
    description: 'Order late at night when most people are asleep.',
    icon: '🌙',
    metric: 'lateNightOrdersCount',
    tiers: [
      { tier: 'bronze', threshold: 3 },
      { tier: 'silver', threshold: 7 },
      { tier: 'gold', threshold: 15 },
      { tier: 'diamond', threshold: 30 },
    ],
  },
  {
    id: 'points_orders',
    label: 'Smart Saver',
    description: 'Use points or discounts effectively on your orders.',
    icon: '🎟️',
    metric: 'pointsOrdersCount',
    tiers: [
      { tier: 'bronze', threshold: 1 },
      { tier: 'silver', threshold: 3 },
      { tier: 'gold', threshold: 5 },
      { tier: 'diamond', threshold: 10 },
    ],
  },
  {
    id: 'big_feast_orders',
    label: 'Feast Mode',
    description: 'Order a large feast with many items in a single order.',
    icon: '🍱',
    metric: 'bigFeastOrdersCount',
    tiers: [
      { tier: 'bronze', threshold: 1 },
      { tier: 'silver', threshold: 3 },
      { tier: 'gold', threshold: 5 },
      { tier: 'diamond', threshold: 10 },
    ],
  },
  {
    id: 'unique_menu_items',
    label: 'Menu Explorer',
    description: 'Try as many different dishes as you can.',
    icon: '🍜',
    metric: 'uniqueMenuItemsCount',
    tiers: [
      { tier: 'bronze', threshold: 5 },
      { tier: 'silver', threshold: 10 },
      { tier: 'gold', threshold: 20 },
      { tier: 'diamond', threshold: 40 },
    ],
  },
  {
    id: 'long_reviews',
    label: 'Storyteller',
    description: 'Write detailed reviews with plenty of feedback.',
    icon: '📖',
    metric: 'longReviewsCount',
    tiers: [
      { tier: 'bronze', threshold: 1 },
      { tier: 'silver', threshold: 3 },
      { tier: 'gold', threshold: 5 },
      { tier: 'diamond', threshold: 10 },
    ],
  },
  {
    id: 'review_diversity',
    label: 'Community Voice',
    description: 'Review many different restaurants in the community.',
    icon: '🗣️',
    metric: 'reviewedRestaurantsCount',
    tiers: [
      { tier: 'bronze', threshold: 2 },
      { tier: 'silver', threshold: 5 },
      { tier: 'gold', threshold: 10 },
      { tier: 'diamond', threshold: 20 },
    ],
  },
];

module.exports = {
  badgeDefinitions,
};
